### ISSUE TITLE
Can't find macro defination "WIN32"

### ISSUE THREAD

**Issue by LovelyCatHyt** [cypok/console_graphics#5]
In Code::Blocks, I can't find the defination of "WIN32", thus making the whole project for Win32 not compiled.It looks like this:
![1](https://user-images.githubusercontent.com/20336911/70851174-f2916d00-1ecc-11ea-955b-7ca3659b7341.png)
![2](https://user-images.githubusercontent.com/20336911/70851176-f9b87b00-1ecc-11ea-9ba8-593c3c94dc70.png)
Or maybe I should modify the compiling settings?

**Comment by cypok** [comment]
Could you replace `WIN32` by `_WIN32` and ensure that everything works as expected?

**Comment by LovelyCatHyt** [comment]
Sorry, I didn't try it before opening this issue.
And now I have found that the CB's parser is to blame, it didn't found this macro but it does exist.
The codes below are compiled.
